services:
  app:
    build: ./
    container_name: app
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    container_name: nginx-smvit
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app